name: Slack Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Notify deploy is finished
        uses: ./
        id: deployment_notification
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK}}
          service_name: Example Service
          action: Finished
          region: us-east-1
