name: Slack Notification
on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify deploy is finished
        uses: ./
        id: deployment_notification
        with:
          webhook: ${{ secrets.SACK_WEBHOOK}}
          service: Example Service
          action: Finished
          region: us-east-1
